<a href="https://colab.research.google.com/github/2303A52164/Generative_ai_2025/blob/main/Generative_AI_2303A52164_Week_No.__Assignment_7_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **7.1 Question:**

In [23]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import h5py
from sklearn.metrics import confusion_matrix, classification_report

In [2]:
df = pd.read_csv('https://drive.google.com/uc?id=1AcdENlVm5dccNyo_vgdMbneX8YVvH5R3')

In [4]:
# Splitting features and target
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [7]:
# Splitting data into train and test sets (80-20 split)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [11]:
# Scaling the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [12]:
# Building the ANN model
model = keras.Sequential([
    keras.layers.Dense(8, activation='relu', input_shape=(X_train.shape[1],)),
    keras.layers.Dense(16, activation='relu'),
    keras.layers.Dense(20, activation='relu'),
    keras.layers.Dense(10, activation='relu'),
    keras.layers.Dense(1, activation='sigmoid')  # Binary classification output
])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [13]:
# Compiling the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [14]:
# Training the model
history = model.fit(X_train, y_train, epochs=150, batch_size=64, validation_data=(X_test, y_test))

Epoch 1/150
7/7 ━━━━━━━━━━━━━━━━━━━━ 3s 74ms/step - accuracy: 0.4129 - loss: 0.5438 - val_accuracy: 0.3578 - val_loss: 0.4667
Epoch 2/150
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.4222 - loss: 0.4846 - val_accuracy: 0.3578 - val_loss: 0.3969
Epoch 3/150
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.4102 - loss: 0.3923 - val_accuracy: 0.3578 - val_loss: 0.3174
Epoch 4/150
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.4378 - loss: 0.3254 - val_accuracy: 0.3578 - val_loss: 0.2329
Epoch 5/150
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.4195 - loss: 0.2450 - val_accuracy: 0.3578 - val_loss: 0.1463
Epoch 6/150
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.4277 - loss: 0.1683 - val_accuracy: 0.3578 - val_loss: 0.0628
Epoch 7/150
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.4209 - loss: 0.1018 - val_accuracy: 0.3578 - val_loss: -0.0190
Epoch 8/150
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.4414 - loss: -0.0870 - val_accuracy: 0.3578 - val_los

In [39]:
model.save("diabetes_ann_model.h5")

In [40]:
# Evaluate model
train_loss, train_acc = model.evaluate(X_train, y_train, verbose=0)
test_loss, test_acc = model.evaluate(X_test, y_test, verbose=0)

In [41]:
print(f"Training Accuracy: {train_acc:.4f}")
print(f"Testing Accuracy: {test_acc:.4f}")

Training Accuracy: 0.4312
Testing Accuracy: 0.3578


In [42]:
# Predictions
y_pred = (model.predict(X_test) > 0.5).astype(int)

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step 


In [43]:
# Confusion matrix
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Confusion Matrix:
 [[ 0 29  0]
 [ 0 39  0]
 [ 0 41  0]]


In [44]:
#classification report
print("Classification Report:\n", classification_report(y_test, y_pred))

Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00        29
           1       0.36      1.00      0.53        39
           2       0.00      0.00      0.00        41

    accuracy                           0.36       109
   macro avg       0.12      0.33      0.18       109
weighted avg       0.13      0.36      0.19       109



/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [49]:
# Load and use the saved model
loaded_model = keras.models.load_model("diabetes_ann_model.h5")

In [52]:
def predict_diabetes(input_data):
    input_data = np.array(input_data).reshape(1, -1)
    input_data = scaler.transform(input_data)
    prediction = loaded_model.predict(input_data)
    return "Diabetic" if prediction[0][0] > 0.5 else "Not Diabetic"

In [53]:
# Example prediction
sample_input = X_test[0]
print("Prediction:", predict_diabetes(sample_input))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step
Prediction: Diabetic


In [35]:
def predict_diabetes(input_data):
    input_data = np.array(input_data).reshape(1, -1)
    input_data = scaler.transform(input_data)
    # Use the trained model 'model' instead of 'loaded_model'
    prediction = model.predict(input_data)
    return "Diabetic" if prediction[0][0] > 0.5 else "Not Diabetic"

In [54]:
# Example prediction
sample_input = X_test[0]
print("Prediction:", predict_diabetes(sample_input))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step
Prediction: Diabetic
